- name: broker group
  group:
    name: "{{ broker.group }}"
  become: yes

- name: broker user
  user:
    name: "{{ broker.user }}"
    comment: "Kafka User"
    system: yes
    group: "{{ broker.group }}"
  become: yes

- name: ensure ownership of the data directory
  file:
    path: "{{ dir }}"
    owner: "{{ broker.user }}"
    group: "{{ broker.group }}"
    state: "directory"
  become: yes
  with_items: "{{ broker.datadir }}"
  loop_control:
    loop_var: dir

- name: broker config
  template:
    src: kafka-broker/server.properties.j2
    dest: "{{ broker.config_file }}"
    mode: 0640
    owner: "{{ broker.user }}"
    group: "{{ broker.group }}"
  notify:
    - restart kafka
  become: yes

- name: kafka broker add env var to service file
  ini_file:
    path: /usr/lib/systemd/system/confluent-kafka.service
    section: Service
    # Mind the quote in option and option ! We want it to be a quoted string in the target file
    option: "Environment='{{ var.key }}"
    value: "{{ var.value }}'"
    no_extra_spaces: yes
  with_dict: "{{ broker.environment }}"
  loop_control:
    loop_var: var
  notify: restart kafka broker with daemon_reload
  become: yes

- name: broker configure service
  systemd:
    name: "{{ broker.service_name }}"
    enabled: "{{ broker.systemd.enabled }}"
    state: "{{ broker.systemd.state }}"
  become: yes

- name: Flush handlers
  meta: flush_handlers
