- name: broker group
  group:
    name: "{{ broker.group }}"
  become: yes

- name: broker user
  user:
    name: "{{ broker.user }}"
    comment: "Kafka User"
    system: yes
    group: "{{ broker.group }}"
  become: yes

- name: ensure ownership of the data directory
  file:
    path: "{{ dir }}"
    owner: "{{ broker.user }}"
    group: "{{ broker.group }}"
    state: "directory"
  become: yes
  with_items: "{{ broker.datadir }}"
  loop_control:
    loop_var: dir

- name: broker config
  template:
    src: kafka-broker/server.properties.j2
    dest: "{{ broker.config_file }}"
    mode: 0640
    owner: "{{ broker.user }}"
    group: "{{ broker.group }}"
  notify:
    - restart kafka
  become: yes

- name: broker configure service
  systemd:
    name: "{{ broker.service_name }}"
    enabled: "{{ broker.systemd.enabled }}"
    state: "{{ broker.systemd.state }}"
  become: yes
