---
sudo: required
language: python
services:
  - docker
before_install:
  - sudo apt-get -qq update
env:
  - SCENARIO="default" ANSIBLE="2.4"
  - SCENARIO="centos" ANSIBLE="2.4"
  - SCENARIO="debian" ANSIBLE="2.4"
  - SCENARIO="default" ANSIBLE="2.5"
  - SCENARIO="centos" ANSIBLE="2.5"
  - SCENARIO="debian" ANSIBLE="2.5"
install: pip install tox-travis
script: tox
