---
sudo: required
language: python
services:
  - docker
before_install:
  - sudo apt-get -qq update
env:
  - SCENARIO="default"
  - SCENARIO="centos"
  - SCENARIO="debian"
  - ANSIBLE="2.4"
  - ANSIBLE="2.5"
install: pip install tox-travis
script: tox
