- name: Gather os specific variables
  include_vars: "{{ ansible_os_family }}.yml"
  tags: vars

# based on default_role, we will import the required sub-roles

# Always import common
- name: "Importing confluent common"
  import_tasks: common/main.yml

- name: "Importing role from confluent_roles"
  include_tasks: "{{ item }}/main.yml"
  with_items: "{{ confluent_roles }}"
#
#- name: "Importing role Zookeeper"
#  import_tasks: "zookeeper/main.yml"
#  when: "'zookeeper' in confluent_roles"
