---
- name: Extract the confluent version
  set_fact:
    confluent_version: "{{ confluent_version | default([]) }} + [ '{{ versionvalue.value }}' ]"
  with_dict: "{{ confluent.version }}"
  loop_control:
    loop_var: versionvalue

- name: Gather os specific variables
  include_vars: "{{ ansible_os_family }}.yml"
  tags: vars

# Always import Common
- name: "Importing confluent common"
  import_tasks: common/main.yml

- name: "Importing role from confluent_roles"
  include_tasks: "{{ item }}/main.yml"
  with_items: "{{ confluent_roles }}"
