- name: Gather os specific variables
  include_vars: "{{ ansible_os_family }}.yml"
  tags: vars

# based on default_role, we will import the required sub-roles

# Always import common
- name: "Importing confluent common"
  import_tasks: common/main.yml

- name: "Importing role {{ item }}"
  imports_tasks: "{{ item }}/main.yml"
  with_items: "{{ confluent_roles }}"
