---
- name: connect distributed create group
  group:
    name: "{{ kafka_connect_distributed_group }}"
  become: yes

- name: connect distributed create user
  user:
    name: "{{ kafka_connect_distributed_user }}"
    comment: "Connect Distributed User"
    system: yes
    group: "{{ kafka_connect_distributed_group }}"
  become: yes

- name: connect distributed create config
  template:
    src: connect-distributed/connect-distributed.properties.j2
    dest: "{{ kafka_connect_distributed_config_file }}"
    mode: 0640
    owner: "{{ kafka_connect_distributed_user }}"
    group: "{{ kafka_connect_distributed_group }}"
  notify:
    - restart connect distributed
  become: yes

- name: connect distributed add env var to service file
  ini_file:
    path: "{{ kafka_connect_distributed_service_file }}"
    section: Service
    # Mind the quote in option and option ! We want it to be a quoted string in the target file
    option: "Environment='{{ var.key }}"
    value: "{{ var.value }}'"
    no_extra_spaces: yes
  with_dict: "{{ kafka_connect_distributed_environment | default({}) }}"
  loop_control:
    loop_var: var
  notify: reload systemd
  become: yes

- name: connect distributed configure service
  systemd:
    name: "{{ kafka_connect_distributed_service_name }}"
    enabled: "{{ kafka_connect_distributed_systemd_enabled }}"
    state: "{{ kafka_connect_distributed_systemd_state }}"
  become: yes
