---
- name: zookeeper create group
  group:
    name: "{{ zookeeper_group }}"
  become: yes

- name: zookeeper create user
  user:
    name: "{{ zookeeper_user }}"
    comment: "Zookeeper User"
    system: yes
    group: "{{ zookeeper_group }}"
  become: yes

- name: Ensure zookeeper data directories are created
  file:
    path: "{{ dir }}"
    state: directory
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_group }}"
    mode: 0750
  become: yes
  with_items:
    - "{{ zookeeper_config_dataDir }}"
    - "{{ zookeeper_config_dataLogDir }}"
  loop_control:
    loop_var: dir

- name: zookeeper myid file
  template:
    src: zookeeper/myid.j2
    dest: "{{ zookeeper_config_dataDir }}/myid"
    mode: 0555
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_group }}"
  become: yes

- name: zookeeper create config
  template:
    src: zookeeper/zookeeper.properties.j2
    dest: "{{ zookeeper_config_file }}"
    mode: 0400
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_group }}"
  become: yes
  notify:
    - restart zookeeper

- name: Zookeeper add env var to service file
  ini_file:
    path: "{{ zookeeper_service_file }}"
    section: Service
    # Mind the quote in option and option ! We want it to be a quoted string in the target file
    option: "Environment='{{ var.key }}"
    value: "{{ var.value }}'"
    no_extra_spaces: yes
  with_dict: "{{ zookeeper_environment | default({}) }}"
  loop_control:
    loop_var: var
  notify: reload systemd
  become: yes

- name: zookeeper configure service
  systemd:
    name: "{{ zookeeper_service_name }}"
    enabled: "{{ zookeeper_systemd_enabled }}"
    state: "{{ zookeeper_systemd_state }}"
  become: yes
