---
- name: yum-clean-all
  command: yum clean all
  args:
    warn: no
  become: yes

- name: reload systemd
  shell: systemctl daemon-reload
  become: yes

- name: restart connect distributed
  systemd:
    name: "{{ kafka_connect_distributed_service_name }}"
    state: restarted
  become: yes

- name: restart mirror-maker service
  systemd:
    name: "{{ kafka_mirror_maker_service_name }}"
    state: restarted
  become: yes

- name: restart control center
  systemd:
    name: "{{ confluent_control_center_service_name }}"
    state: restarted
  become: yes

- name: restart kafka
  systemd:
    name: "{{ kafka_broker_service_name }}"
    state: restarted
  become: yes

- name: restart kafka-rest
  systemd:
    name: "{{ kafkarest_service_name }}"
    state: restarted
  become: yes

- name: restart ksql
  systemd:
    name: "{{ ksql_service_name }}"
    state: restarted
  become: yes

- name: restart schema-registry
  systemd:
    name: "{{ schema_registry_service_name }}"
    state: restarted
  become: yes

- name: restart zookeeper
  systemd:
    name: "{{ zookeeper_service_name }}"
    state: restarted
  become: yes
