- name: Gather facts for all inventory
  hosts: zookeeper, broker, schema-registry, connect-distributed, control-center, kafka-rest, ksql
  gather_facts: yes
  no_log: yes
  tags:
    - always

- name: Deploy Zookeepers instances
  hosts: zookeepers
  vars:
    - hosts:
        zookeepers: "{{ groups['zookeeper'] }}"
        kafka:
          brokers: "{{ groups['brokers'] }}"
        schema:
          registries: "{{ groups['brokers'] }}"
    - confluent_roles:
      - zookeeper
      - kafka-broker
      - kafka-rest
      - schema-registry
      - connect-distributed
  roles:
    - role: confluent_inc.confluent-platform
  tags:
    - confluent_pf

- name: Deploy Control Center instances
  hosts: control-center
  vars:
    - hosts:
       kafka:
         brokers: "{{ groups['brokers'] }}"
    - confluent_roles:
        - control-center
  roles:
    - role: confluent_inc.confluent-platform
  tags:
    - control-center

- name: Deploy ksql instances
  hosts: ksql
  vars:
   - hosts:
       kafka:
         brokers: "{{ groups['brokers'] }}"
    - confluent_roles:
        - ksql
  roles:
    - role: confluent_inc.confluent-platform
  tags:
    - ksql
