- name: Gather facts for all inventory
  hosts: zookeeper, broker, schema-registry, connect-distributed, control-center, kafka-rest, ksql
  gather_facts: yes
  no_log: yes
  tags:
    - always

- name: Deploy Zookeepers instances
  hosts: zookeeper
  vars:
    - zookeepers: "{{ groups['zookeeper'] }}"
    - confluent_roles:
        - zookeeper
  roles:
    - role: confluent_inc.confluent-platform
  tags:
    - zookeeper

- name: Deploy Brokers instances
  hosts: broker
  vars:
    - zookeepers: "{{ groups['zookeeper'] }}"
    - confluent_roles:
        - broker
  roles:
    - role: confluent_inc.confluent-platform
  tags:
    - broker

- name: Deploy Schema registries instances
  hosts: schema-registry
  vars:
    - brokers: "{{ groups['broker'] }}"
    - confluent_roles:
        - schema-registry
  roles:
    - role: confluent_inc.confluent-platform
  tags:
    - schema-registry

- name: Deploy Connect distributed instances
  hosts: connect-distributed
  vars:
    - brokers: "{{ groups['broker'] }}"
    - registries: "{{ groups['broker'] }}"
    - confluent_roles:
        - connect-distributed
  roles:
    - role: confluent_inc.confluent-platform
  tags:
    - connect-distributed

- name: Deploy Control Center instances
  hosts: control-center
  vars:
    - brokers: "{{ groups['broker'] }}"
    - confluent_roles:
        - control-center
  roles:
    - role: confluent_inc.confluent-platform
  tags:
    - control-center

- name: Deploy Kafka Rest instances
  hosts: kafka-rest
  vars:
    - brokers: "{{ groups['broker'] }}"
    - confluent_roles:
        - kafka-rest
  roles:
    - role: confluent_inc.confluent-platform
  tags:
    - kafka-rest

- name: Deploy ksql instances
  hosts: ksql
  vars:
    - brokers: "{{ groups['broker'] }}"
    - confluent_roles:
        - ksql
  roles:
    - role: confluent_inc.confluent-platform
  tags:
    - ksql
