---
- name: schema-registry create group
  group:
    name: "{{ schema_registry_group }}"
  become: yes

- name: schema-registry create user
  user:
    name: "{{ schema_registry_user }}"
    comment: "Schema Registry User"
    system: yes
    group: "{{ schema_registry_group }}"
  become: yes

- name: schema-registry create config
  template:
    src: schema-registry/schema-registry.properties.j2
    dest: "{{ schema_registry_config_file }}"
    mode: 0640
    owner: "{{ schema_registry_user }}"
    group: "{{ schema_registry_group }}"
  notify:
    - restart schema-registry
  become: yes

- name: Schema registry add env var to service file
  ini_file:
    path: "{{ schema_registry_service_file }}"
    section: Service
    # Mind the quote in option and option ! We want it to be a quoted string in the target file
    option: "Environment='{{ var.key }}"
    value: "{{ var.value }}'"
    no_extra_spaces: yes
  with_dict: "{{ schema_registry_environment | default({}) }}"
  loop_control:
    loop_var: var
  notify: reload systemd
  become: yes

- name: schema-registry configure service
  systemd:
    name: "{{ schema_registry_service_name }}"
    enabled: "{{ schema_registry_systemd_enabled }}"
    state: "{{ schema_registry_systemd_state }}"
  become: yes
