# TODO: Add a var that tell if we want jre/jdk to be managed by this role
- name: Install Java
  yum:
    name: "openjdk8-jre"
    state: latest
  become: yes

- name: Disable Require TTY in Sudoers (required for ansible synchronize)
  lineinfile:
    path: /etc/sudoers
    state: absent
    regexp: '^Defaults\s+requiretty.*$'
  become: yes

- name: Add an Apt signing key
  apt_key:
    url: "http://packages.confluent.io/deb/{{ confluent.version.major }}.{{ confluent.version.minor }}/archive.key"
    state: present
  become: yes

- name: Add apt Repository
  apt_repository:
    repo: "deb http://packages.confluent.io/deb/{{ confluent.version.major }}.{{ confluent.version.minor }} stable main"
    state: present
  become: yes
