---
- name: Install Java
  package:
    name: "{{ openjdk_package }}"
    state: present
  become: yes

- name: Disable Require TTY in Sudoers (required for ansible synchronize)
  lineinfile:
    path: /etc/sudoers
    state: absent
    regexp: '^Defaults\s+requiretty.*$'
  become: yes

- name: Check current confluent version
  shell: find /usr/share/java/kafka -name \*kafka_\* | head -1 | grep -o '\kafka[^\n]*' | awk -F '-' '{ print $2}' | awk -F '.' '{print $1"."$2}'
  become: yes
  register: confluent_current_version

- name: Stop Confluent process
  service:
    name: confluent-kafka
    state: stopped
  become: yes
  when: confluent_current_version.stdout_lines[0] != confluent_new_version

# Import Distribution Specific tasks
- name: "Include os {{ ansible_os_family }} specific"
  include_tasks: "{{ ansible_os_family }}.yml"

- name: Install the Confluent Platform
  package:
    name: "{{ package_name }}"
    state: "{% if confluent_latest %}latest{% else %}present{% endif %}"
  become: yes

- import_tasks: ssl_certs.yml
  when: security_mode == "ssl" or security_mode == "sasl_ssl"
