---
- name: Install Java
  package:
    name: "{{ openjdk_package }}"
    state: present
  become: yes

- name: Disable Require TTY in Sudoers (required for ansible synchronize)
  lineinfile:
    path: /etc/sudoers
    state: absent
    regexp: '^Defaults\s+requiretty.*$'
  become: yes

- name: Check current confluent version
  shell: dpkg -l | egrep "ii|iU" | grep confluent-kafka-[0-9] | awk '{ print $3 }' | cut -d . -f -2
  become: yes
  register: confluent_current_version
  tags:
    - kafka-upgrade

- name: Stop Confluent process because package upgrade
  service:
    name: confluent-kafka
    state: stopped
  become: yes
  when:
    - confluent_current_version.stdout_lines
    - confluent_current_version.stdout_lines[0] != confluent_new_version
    - confluent_new_version != '5.0'
  tags:
    - kafka-upgrade

# Import Distribution Specific tasks
- name: "Include os {{ ansible_os_family }} specific"
  include_tasks: "{{ ansible_os_family }}.yml"

- name: Install the Confluent Platform
  package:
    name: "{{ package_name }}"
    state: "{% if confluent_latest %}latest{% else %}present{% endif %}"
  become: yes

- import_tasks: ssl_certs.yml
  when: security_mode == "ssl" or security_mode == "sasl_ssl"
