
- name: "Include os {{ ansible_os_family }} specific"
  include_tasks: "{{ ansible_os_family }}.yml"

- name: "Include SSL Stuff"
  include_tasks: ssl_certs.yml
  when: security_mode == "ssl" or security_mode == "sasl_ssl"


