---
- name: Deploy and configure Zookeepers
  hosts: zookeepers
  vars:
    - confluent_roles:
        - zookeeper
    - hosts_zookeepers:
        - server1:2181
        - server2:2181
  roles:
    - role: cp-ansible

- name: Deploy and configure brokers
  hosts: brokers
  vars:
    - confluent_roles:
        - kafka-broker
    - hosts_zookeepers:
        - server1:2181
        - server2:2181
    - hosts_kafka_brokers: "{{ groups['brokers'] }}"
  roles:
    - role: cp-ansible
