---
#- name: Setup hosts and install required packages for the test scenario
#  hosts: all
#  gather_facts: yes
#

#- name: Install Confluent PF on all hosts
#  hosts: all
#  roles:
#    - role: cp-ansible

- name: Deploy and configure Zookeepers
  hosts: zookeepers
  vars:
    - confluent_roles:
        - zookeeper
    - hosts:
        zookeepers: "{{ groups['zookeepers'] }}"
  roles:
    - role: cp-ansible

- name: Deploy and configure brokers
  hosts: brokers
  vars:
    - confluent_roles:
        - kafka-broker
    - hosts:
        zookeepers: "{{ groups['zookeepers'] }}"
        kafka:
          brokers: "{{ groups['brokers'] }}"
  roles:
    - role: cp-ansible
