---
- name: Prepare
  hosts: all
  gather_facts: true
  tasks:
    - name: install required packages
      package:
        name: "{{ item }}"
        state: present
        update_cache: yes
        use: apt
      with_items:
#        - python2
        - net-tools
        - netcat
#        - sudo
